services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: react_frontend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - ..:/app
    command: ["pnpm", "run", "dev"]
