version: '3'
services:
  db:
    image: postgres:latest
    container_name: token-commerce_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-peranum}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-18051}
      POSTGRES_DB: ${POSTGRES_DB:-your_database}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_URL: ${REDIS_URL:-redis://localhost:6379}
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network

  backend-service:
    build:
      context: ./backend
    depends_on:
      - redis
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER:-peranum}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-18051}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

  frontend-service:
    build:
      context: ./frontend
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
