services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: nest_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nest
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: ["pnpm", "run", "start:dev"]
    profiles:
      - backend
      - full

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - backend
      - full

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: react_frontend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
    command: ["pnpm", "run", "dev"]
    profiles:
      - frontend
      - full

volumes:
  postgres_data:
