services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_DB: ${POSTGRES_DB:-your_database}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_URL: ${REDIS_URL:-redis://localhost:6379}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
